### PR TITLE
Add limitations and known issues section

### PR DESCRIPTION
**Pull request by wnvko**
Add known issues and limitations section in Blazor support topic

### CODE REVIEW

**Review by Lipata — APPROVED** [review]

**Review by zdrawku — COMMENTED** [review]
Nice, that would be of great value. What about a list of the supported components? We taked abiyt a table with checkboxes, based on a framework. I know that it would be time consuming to create such and a bit hard to be maintained, but I think it would be of great value. We can think of adding a references to already maintained lists or whatever other suggestions you have?

**Comment by wnvko** [comment]
@zdrawku
It will be great to have a table showing all supported components against platform they are supported for generation. It could be something like this:

| Component | Angular | Blazor |
|--------------|-----------|--------|
| Button  | :white_check_mark:|:white_check_mark:|
| Combo | :white_check_mark:|:x:|

This will allow us to add more platforms once we have them.

I think the best place for such a table is in [Generate App](https://www.infragistics.com/products/appbuilder/help/generate-app/generate-app-overview) section, and not in some custom platform section.

**Comment by zdrawku** [comment]
> @zdrawku It will be great to have a table showing all supported components against platform they are supported for generation. It could be something like this:
> 
> Component	Angular	Blazor
> Button	✅	✅
> Combo	✅	❌
> This will allow us to add more platforms once we have them.
> 
> I think the best place for such a table is in [Generate App](https://www.infragistics.com/products/appbuilder/help/generate-app/generate-app-overview) section, and not in some custom platform section.

Yes, sounds good, lets do that

**Review by Lipata — APPROVED** [review]

**Review by zdrawku — APPROVED** [review]
Looks great @wnvko well done:

image

**Pull request merged**
